services:
  - docker

script:
  - docker-compose up

before_deploy:
  - docker-compose up

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: docs
    target_branch: master
    on:
      branch: hugo-site
