dist: xenial
language: go
go:
  - "1.11"

sudo: required

addons:
 snaps:
   name: hugo
   channel: extended

script:
  - hugo

before_deploy:
  - hugo

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: docs
    on:
      branch: master
