language: go
go:
  - "1.11"

git:
  depth: 10

sudo: required

before_install:
  - snap install hugo --channel=extended

script:
  - hugo

before_deploy:
  - hugo

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: docs
    on:
      branch: master
