dist: trusty
services:
  - docker

before_deploy:
  - docker-compose up
  
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: docs
    on:
      branch: master
