language: go
go:
  - "1.12"

sudo: required

before_install:
  - sudo apt-get install -y hugo

script:
  - hugo

before_deploy:
  - hugo

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: docs
    on:
      branch: master
