baseURL: "https://ccv.brown.edu/ccvcon"
languageCode: "en-us"
title: "CCV·Con"
theme: brown-simple
publishDir: docs

params:
  title: CCV·Con
  full_title: Center for Computation & Visualization Conference
  year: "'19"
  subtitle: not just Oscar
  info:
    date:
      start: Monday Oct 28
      end:  Friday Nov 1
      time_start: 3 - 5pm
    location:
      building: Data Science Initiative - 164 Angell Street, 3rd Floor, Brown University
      city: Providence, RI
  program:
    - time: Monday, October 28
      session: Reproducible Science
      title: Reproducible Science
      speaker: Isabel Restrepo
    - time: Tuesday, October 29
      session: Secure Computing + Visualization
      title: Secure Computing + Visualization
      speaker: Mete Tunca, Ben Knörlein
    - time: Wednesday, October 30
      session: Data Science + Machine Learning
      title: Data Science + Machine Learning
      speaker: Andras Zsom, Paul Stey
    - time: Thursday, October 31
      session: High Performance Computing
      title: High Performance Computing
      speaker: Helen Kershaw
    - time: Friday, November 1
      session: Not Just Oscar Pannel + Keynote
      title: Not Just Oscar Pannel + Keynote + Reception
      speaker: Linnea Wolfe, Paul Stey, Mete Tunca, Thomas Serre
