baseURL: "https://ccv.brown.edu/ccvcon"
languageCode: "en-us"
title: "CCV·Con"
theme: brown-simple
publishDir: docs

params:
  title: CCV·Con
  full_title: Center for Computation & Visualization Conference
  year: "'19"
  subtitle: not just Oscar
  info:
    date:
      start: Monday Oct 28
      end:  Friday Nov 1
      time_start: 3 - 5pm
    location:
      building: Data Science Initiative - 164 Angell Street, 3rd Floor
      city: Brown University – Providence, RI
  program:
    - time: Monday
      session: Data + Visualization
      title: Data + Visualization
      speaker: Isabel Restrepo, Ben Knörlein
    - time: Tuesday
      session: Secure Computing
      title: Secure Computing
      speaker: Mete Tunca
    - time: Wednesday
      session: Data Science + Machine Learning
      title: Data Science + Machine Learning
      speaker: Andras Zsom, Paul Stey
    - time: Thursday
      session: High Performance Computing
      title: High Performance Computing
      speaker: Helen Kershaw
    - time: Friday
      session: Keynote
      title: Keynote + Reception
      speaker: Thomas Serre
