baseURL: "https://ccvcon.brown.edu"
languageCode: "en-us"
title: "CCVConf"
theme: brown-simple
publishDir: docs

params:
  title: CCVCon
  year: "'19"
  subtitle: not just Oscar
  hero:
    - FALL 2019
