baseURL: "https://ccvcon.brown.edu"
languageCode: "en-us"
title: "CCVConf"
theme: brown-simple
publishDir: docs

params:
  title: CCVCon
  year: "'19"
  subtitle: not just Oscar
  hero:
    date:
      day: 18
      dow: Fri
      month: Oct
      year: 2019
    location:
      building: Engineering Research Center
      city: Brown University – Providence, RI
